[2024-06-26 06:45:55,454] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: etl_pipeline_smoking_cost.transform_task_01 2024-06-26T06:45:41.321218+00:00 [queued]>
[2024-06-26 06:45:55,505] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: etl_pipeline_smoking_cost.transform_task_01 2024-06-26T06:45:41.321218+00:00 [queued]>
[2024-06-26 06:45:55,506] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2024-06-26 06:45:55,507] {taskinstance.py:1069} INFO - Starting attempt 1 of 1
[2024-06-26 06:45:55,507] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2024-06-26 06:45:55,529] {taskinstance.py:1089} INFO - Executing <Task(PythonOperator): transform_task_01> on 2024-06-26T06:45:41.321218+00:00
[2024-06-26 06:45:55,541] {standard_task_runner.py:52} INFO - Started process 49 to run task
[2024-06-26 06:45:55,587] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'etl_pipeline_smoking_cost', 'transform_task_01', '2024-06-26T06:45:41.321218+00:00', '--job-id', '88', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline_smoking_cost.py', '--cfg-path', '/tmp/tmpvwvr5jas', '--error-file', '/tmp/tmpayyo3ben']
[2024-06-26 06:45:55,594] {standard_task_runner.py:77} INFO - Job 88: Subtask transform_task_01
[2024-06-26 06:45:55,774] {logging_mixin.py:104} INFO - Running <TaskInstance: etl_pipeline_smoking_cost.transform_task_01 2024-06-26T06:45:41.321218+00:00 [running]> on host 471e920996d3
[2024-06-26 06:45:55,836] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1275, in _prepare_and_execute_task_with_callbacks
    self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1779, in render_templates
    self.task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 892, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 905, in _do_render_template_fields
    rendered_content = self.render_template(content, context, jinja_env, seen_oids)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 956, in render_template
    return [self.render_template(element, context, jinja_env) for element in content]
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 956, in <listcomp>
    return [self.render_template(element, context, jinja_env) for element in content]
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 942, in render_template
    return jinja_env.from_string(content).render(**context)
  File "/home/airflow/.local/lib/python3.6/site-packages/jinja2/environment.py", line 941, in from_string
    return cls.from_code(self, self.compile(source), globals, None)
  File "/home/airflow/.local/lib/python3.6/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/home/airflow/.local/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/airflow/.local/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected char '"' at 36
[2024-06-26 06:45:55,848] {taskinstance.py:1532} INFO - Marking task as FAILED. dag_id=etl_pipeline_smoking_cost, task_id=transform_task_01, execution_date=20240626T064541, start_date=20240626T064555, end_date=20240626T064555
[2024-06-26 06:45:55,916] {local_task_job.py:146} INFO - Task exited with return code 1
