[2024-06-26 02:27:15,937] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: etl_pipeline_smoking_cost.transform_task_01 2024-06-26T02:24:57.979450+00:00 [queued]>
[2024-06-26 02:27:16,001] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: etl_pipeline_smoking_cost.transform_task_01 2024-06-26T02:24:57.979450+00:00 [queued]>
[2024-06-26 02:27:16,002] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2024-06-26 02:27:16,003] {taskinstance.py:1069} INFO - Starting attempt 1 of 1
[2024-06-26 02:27:16,004] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2024-06-26 02:27:16,035] {taskinstance.py:1089} INFO - Executing <Task(PythonOperator): transform_task_01> on 2024-06-26T02:24:57.979450+00:00
[2024-06-26 02:27:16,054] {standard_task_runner.py:52} INFO - Started process 45 to run task
[2024-06-26 02:27:16,081] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'etl_pipeline_smoking_cost', 'transform_task_01', '2024-06-26T02:24:57.979450+00:00', '--job-id', '86', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline_smoking_cost.py', '--cfg-path', '/tmp/tmpadgwkskq', '--error-file', '/tmp/tmpofohax7o']
[2024-06-26 02:27:16,082] {standard_task_runner.py:77} INFO - Job 86: Subtask transform_task_01
[2024-06-26 02:27:16,321] {logging_mixin.py:104} INFO - Running <TaskInstance: etl_pipeline_smoking_cost.transform_task_01 2024-06-26T02:24:57.979450+00:00 [running]> on host 471e920996d3
[2024-06-26 02:27:16,481] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=etl_pipeline_smoking_cost
AIRFLOW_CTX_TASK_ID=transform_task_01
AIRFLOW_CTX_EXECUTION_DATE=2024-06-26T02:24:57.979450+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-06-26T02:24:57.979450+00:00
[2024-06-26 02:27:16,488] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: transform_task() missing 1 required positional argument: 'data'
[2024-06-26 02:27:16,504] {taskinstance.py:1532} INFO - Marking task as FAILED. dag_id=etl_pipeline_smoking_cost, task_id=transform_task_01, execution_date=20240626T022457, start_date=20240626T022715, end_date=20240626T022716
[2024-06-26 02:27:16,970] {local_task_job.py:146} INFO - Task exited with return code 1
